services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dumbmerch
      POSTGRES_PASSWORD: devops123
      POSTGRES_DB: dumbmerch
    ports:
      - "5432:5432" 
    volumes:
      - /opt/dumbmerch/postgres-data:/var/lib/postgresql/data
    networks:
      - dumbmerch-network

networks:
  dumbmerch-network:
    name: dumbmerch-network
    driver: bridge
