---
- hosts: appserver, gateway
  name: "install server monitoring"
  vars:
    locale: ~/ansible
    remote: /home/fauzan/monitoring
  tasks:
    - copy:
        dest: "{{remote}}/prometheus.yml"
        src: "{{locale}}/config/prometheus.yml"
      name: "send prometheus config"

    - copy:
        dest: "{{remote}}/compose-monitoring.yml"
        src: "{{locale}}/dockerstuff/compose-monitoring.yml"
      name: "send compose to server"

    - community.docker.docker_compose_v2:
        files:
          - compose-monitoring.yml
        project_name: monitoring
        project_src: "{{remote}}"
        remove_orphans: true
      name: "run docker compose"
