---
- vars:
    locale: ~/automation/ansible
    remote: /home/devops/monitoring
  hosts: appserver2, gateway, monitoring
  name: "Install node exporter"
  tasks:
    -
      file:
        path: /home/devops/monitoring/
        state: directory
    -
      copy:
        dest: "{{remote}}/docker-compose.yml"
        src: "{{locale}}/dockerstuff/node-exporter.yml"
      name: "sending compose.yml"
    -
      community.docker.docker_compose_v2:
        files:
          - node-exporter.yml
        project_name: monitoring
        project_src: "{{remote}}"
      name: "run docker compose"
